{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{instance=\"metabase:3301\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Heap: used by the application\nNon-heap: used by the JVM for odds and ends",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"metabase:3300\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"metabase:3300\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "c3p0_num_connections{instance=\"metabase:3300\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Threads by state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"metabase:3300\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Jetty stats",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "jetty_async_requests_waiting{instance=\"metabase:3300\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jetty_dispatched_active{instance=\"metabase:3300\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jetty_expires_total{instance=\"metabase:3300\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "jetty_requests_active{instance=\"metabase:3300\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Spans",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "filters": [
      {
       "id": "b94ad4a6",
       "operator": "=~",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "metabase" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [
        "GET",
        "POST",
        "PUT"
       ],
       "valueType": "string"
      }
     ],
     "groupBy": [
      { "id": "d4bc16dd", "scope": "span" }
     ],
     "limit": 20,
     "spss": 3,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "flamegraph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "labelSelector": "{service_name=\"metabase\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "RAM consumption",
   "type": "flamegraph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "labelSelector": "{service_name=\"metabase\"}",
     "profileTypeId": "memory:alloc_in_new_tlab_bytes:bytes:space:bytes"
    }
   ]
  },
  {
   "title": "Mutex waits",
   "type": "flamegraph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "labelSelector": "{service_name=\"metabase\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "Mutex contentions",
   "type": "flamegraph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "labelSelector": "{service_name=\"metabase\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{source=\"metabase\"}"
    }
   ]
  }
 ]
}